open_malaysia:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: darwin
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: open_malaysia
      schema: public
      threads: 2
    prod:
      type: postgres
      host: dpg-d6vpbcchg0os739uh4m0-a.singapore-postgres.render.com
      port: 5432
      user: open_malaysia_user
      password: "{{ env_var('RENDER_DB_PASSWORD') }}"
      dbname: open_malaysia
      schema: dbt_default
      threads: 2
