services:
  postgres:
    image: postgres:16
    container_name: open_malaysia_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: open_malaysia_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres


volumes:
  postgres_data:
